// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // استفاده از Local Storage برای ذخیره نشست
    persistSession: true, // اطمینان از ذخیره نشست
    autoRefreshToken: true, // رفرش خودکار توکن‌ها
    detectSessionInUrl: true, // تشخیص نشست از URL (برای OAuth)
    flowType: 'pkce', // نوع جریان احراز هویت
  },
});