// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hhtaykuurboewbowzesa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodGF5a3V1cmJvZXdib3d6ZXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Njc1NTQsImV4cCI6MjA2OTQ0MzU1NH0.MXO2A0tXOudBS7jiKDlYuc92t5gNBhIVvp_1kSkcdcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);