name: Build Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build web app
      run: pnpm run build

    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: dist/

  build-desktop:
    runs-on: windows-latest
    needs: build-web
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Increase file limits (Windows)
      shell: powershell
      run: |
        # افزایش محدودیت فایل‌های باز برای جلوگیری از EMFILE
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" -Name "MaxConnectionsPerServer" -Value 100
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" -Name "MaxConnectionsPer1_0Server" -Value 100

        # افزایش محدودیت‌های سیستم برای فایل‌های باز
        $regPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\I/O System"
        if (Test-Path $regPath) {
          Set-ItemProperty -Path $regPath -Name "PagedPoolSize" -Value 0xFFFFFFFF -Type DWORD -Force
          Set-ItemProperty -Path $regPath -Name "NonPagedPoolSize" -Value 0xFFFFFFFF -Type DWORD -Force
        }

        # تنظیم متغیرهای محیطی برای افزایش محدودیت فایل‌ها
        $env:UV_THREADPOOL_SIZE = 128
        $env:NODE_OPTIONS = "--max-old-space-size=8192"
        Write-Host "File limits increased"

    - name: Download web build artifacts
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: dist/

    - name: Build Electron app for Windows
      run: pnpm run build-win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UV_THREADPOOL_SIZE: 128
        NODE_OPTIONS: "--max-old-space-size=8192"

    - name: Upload desktop build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: desktop-app-windows
        path: dist-electron/

    - name: Create Release (optional, only on push to main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release for desktop app.
        draft: false
        prerelease: false
        files: ./dist-electron/**/*
