name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build web app
      run: pnpm run build

    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build-android
        path: dist/

  build-android:
    runs-on: ubuntu-latest
    needs: build-web
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Download web build artifacts
      uses: actions/download-artifact@v4
      with:
        name: web-build-android
        path: dist/

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.0
        ndk: 25.2.9519653
        cmake: 3.22.1

    - name: Fix gradlew permissions
      run: chmod +x android/gradlew

    - name: Setup Capacitor
      run: |
        pnpm run cap:sync

    - name: Build Android APK
      run: |
        pnpm run cap:build:android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/
        retention-days: 1

    - name: Create Release (if on main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Android build completed!"
